language: python

python:
  - "3.6"

branches:
  only:
    - master
    - 0.1.x

before_install:
  # http://conda.pydata.org/docs/travis.html
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
  - source activate test-environment
  - conda install numpy scipy matplotlib pandas tqdm
  - pip install coverage pytest pytest-cov codecov

install:
  - pip install --no-deps .  # Test installation correctness

script:
  - py.test -vv  # Test against installed code

after_success:
  # Uninstall to test coverage against sources
  - pip uninstall pyfme -y
  - pip install --no-deps -e .
  - py.test --cov
  - codecov
